[package]
name = "reap-sow-macros"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits", "full", "visit-mut"] }
quote = "*"
proc-macro2 = "*"
r3bl_rs_utils = "*"
